SET FOREIGN_KEY_CHECKS=0; 
SHOW FULL TABLES FROM `taxi_dev` WHERE table_type = 'BASE TABLE';
DROP TABLE `taxi_dev`.`DATABASECHANGELOG`; 
DROP TABLE `taxi_dev`.`DATABASECHANGELOGLOCK`; 
DROP TABLE `taxi_dev`.`jhi_authority`; 
DROP TABLE `taxi_dev`.`jhi_persistent_audit_event`; 
DROP TABLE `taxi_dev`.`jhi_persistent_audit_evt_data`; 
DROP TABLE `taxi_dev`.`jhi_user`; 
DROP TABLE `taxi_dev`.`jhi_user_authority`; 
DROP TABLE `taxi_dev`.`t_attachment`; 
DROP TABLE `taxi_dev`.`t_capture`; 
DROP TABLE `taxi_dev`.`t_city`; 
DROP TABLE `taxi_dev`.`t_comment`; 
DROP TABLE `taxi_dev`.`t_conduire`; 
DROP TABLE `taxi_dev`.`t_organisation`; 
DROP TABLE `taxi_dev`.`t_passager`; 
DROP TABLE `taxi_dev`.`t_passager_coordonnees`; 
DROP TABLE `taxi_dev`.`t_photo`; 
DROP TABLE `taxi_dev`.`t_photo_profile`; 
DROP TABLE `taxi_dev`.`t_score`; 
DROP TABLE `taxi_dev`.`t_taxi_driver`; 
DROP TABLE `taxi_dev`.`t_vehicule`; 
SELECT `TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA` = 'taxi_dev' AND `TABLE_TYPE` = 'VIEW'; 
SELECT `SPECIFIC_NAME` FROM `INFORMATION_SCHEMA`.`ROUTINES` WHERE `ROUTINE_SCHEMA` = 'taxi_dev' AND ROUTINE_TYPE = 'PROCEDURE'; 
SELECT `SPECIFIC_NAME` FROM `INFORMATION_SCHEMA`.`ROUTINES` WHERE `ROUTINE_SCHEMA` = 'taxi_dev'AND ROUTINE_TYPE = 'FUNCTION'; 
SELECT `EVENT_NAME` FROM `INFORMATION_SCHEMA`.`EVENTS` WHERE `EVENT_SCHEMA` = 'taxi_dev' ORDER BY EVENT_NAME; 
SET FOREIGN_KEY_CHECKS=1; 

